import Head from 'next/head'
import Image from 'next/image'
/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import TopPage from './toppage';

export default function Home() {
  return (
    <>
      <Head>
        <title>ログインを試してみる</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopPage/>
    </>
  )
}


